import express from "express";
import cors from "cors";
import helmet from "helmet";
import dotenv from "dotenv";
import appointmentRoutes from "./routes/appointment.routes";
dotenv.config();
const app = express();
const PORT = process.env.PORT || 3003;
app.use(helmet()); app.use(cors()); app.use(express.json({ limit: "10mb" }));
app.use("/api/appointments", appointmentRoutes);
app.get("/health", (req, res) => res.json({ status: "ok", service: "appointment-service" }));
app.listen(PORT, () => console.log(`Appointment Service started on port ${PORT}`));
export default app;
